import { createRouter, createWebHistory } from "vue-router";

// Routes generated by vite-plugin-pages
import routes from "~pages";

// Routes manually configured
// import routes from "./oldRoutes.ts"

export const router = createRouter({
  history: createWebHistory(),
  routes,
});
